#!/usr/bin/env ruby

unless Kernel.respond_to?(:require_relative)
  module Kernel
    def require_relative(path)
      require File.expand_path(path.to_str, File.dirname(caller[0]))
    end
  end
end

require_relative 'lib/cmd_runner'

if __FILE__ == $0
  trap("SIGINT") { puts "\nGoodbye!"; exit! }
  XRay::CMDRunner.run
end

